name: psdag03
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.13
  - numpy=1.21.5
  - pandas=1.4.2
  - scikit-learn=1.0.2
  - matplotlib=3.5.1
  - scipy=1.7.3
  - seaborn=0.11.2
  - tsfresh=0.18.0
  - jupyterlab=3.3.2
  - openpyxl=3.0.9
